import React,{useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen} from 'lucide-react';

const typeOf=p=>String(p?.type||p?.category||'').toLowerCase().includes('attar')?'Attar':'Perfume';
const img=p=>{const v=p?.images?.[0]||p?.image||'';return v?`/products/${String(v).split('/').pop().replace(/\.(png|jpe?g)$/i,'.webp')}`:'/products/placeholder.webp';};
const notes=p=>[p?.top,p?.mid,p?.base].filter(Boolean);
function useProducts(){const [items,setItems]=useState([]);useEffect(()=>{const sync=()=>setItems(window.EE?.getProducts?.()||[]);sync();const id=setInterval(sync,600);return()=>clearInterval(id);},[]);return items;}
function articleFor(slug,products){
  const perfumes=products.filter(p=>typeOf(p)==='Perfume');
  const fresh=perfumes.find(p=>/fresh|aquatic|citrus|marine/i.test(`${p.accords} ${p.family}`))||perfumes[1]||products[0];
  const deep=products.find(p=>/oud|woody|amber|musk/i.test(`${p.accords} ${p.family}`))||products[0];
  const lead=perfumes.find(p=>p!==deep)||perfumes[0]||products[0];
  if(slug==='fresh-fragrance-for-warm-weather')return {tag:'WARM WEATHER',title:`When to wear ${fresh?.name||'a fresh profile'}`,product:fresh,dek:'A practical edit for bright openings, warm afternoons and clean dry-downs.',sections:[['Start with the opening',`${fresh?.top||'Citrus and aromatic notes'} create the first impression. Spray lightly on moisturised skin and let the opening settle before judging the blend.`],['Follow the heart',`${fresh?.mid||'A transparent heart'} gives the fragrance its personality. Fresh profiles can feel especially clear in heat, so use a lighter hand and refresh when needed.`],['Finish with the base',`${fresh?.base||'A clean base'} is what remains closest to the skin. Your result will vary with skin chemistry, clothing, humidity and application.`]]};
  if(slug==='woods-oud-and-evening-wear')return {tag:'DEPTH & LASTING',title:`An evening edit around ${deep?.name||'woods and oud'}`,product:deep,dek:'How to build a warmer, more textured scent wardrobe from the base notes upward.',sections:[['Look for the anchor',`${deep?.base||deep?.family||'Oud, woods and amber'} give an evening fragrance its sense of depth. Start with one spray, then build gradually.`],['Give the heart time',`${deep?.mid||'Spices and florals'} can change noticeably as the opening fades. Wait a few minutes before layering another profile.`],['Wear it with care','Apply to moisturised pulse points and, if suitable for the fabric, lightly mist clothing from a distance. Lasting is an estimate—not a guarantee—and depends on environment and wear conditions.']]};
  return {tag:'NOTE MAP',title:`${lead?.name||'A signature scent'} from opening to dry-down`,product:lead,dek:'A simple way to read the fragrance pyramid before choosing a bottle or a custom set.',sections:[['Opening / top notes',`${lead?.top||'The top notes'} are the first impression: bright, quick and designed to invite you in.`],['Heart notes',`${lead?.mid||'The heart notes'} emerge as the opening softens and define the blend’s central character.`],['Base notes',`${lead?.base||'The base notes'} create the lasting impression. Compare this stage across products when building your personal wardrobe.`]]};
}
export default function JournalPage({slug,onBack}){
  const products=useProducts();
  const article=useMemo(()=>articleFor(slug,products),[slug,products]);
  if(!products.length)return <div className="ee-journal-loading">Loading the journal…</div>;
  return <main className="ee-journal-page"><div className="ee-journal-toolbar"><button onClick={onBack}><ArrowLeft size={16}/> Home</button><span><BookOpen size={15}/> Eternal Essence Journal</span></div><article className="ee-journal-article"><div className="ee-journal-kicker">{article.tag}</div><h1>{article.title}</h1><p className="ee-journal-dek">{article.dek}</p>{article.product&&<div className="ee-journal-product"><img src={img(article.product)} alt={article.product.name}/><div><span>{article.product.family||'SIGNATURE PROFILE'}</span><strong>{article.product.name}</strong><small>{notes(article.product).join(' · ')}</small><button onClick={()=>window.eeNavigateToProduct?.(article.product.id||article.product._id)}>VIEW THIS FRAGRANCE <ArrowRight size={15}/></button></div></div>}<div className="ee-journal-body">{article.sections.map(([heading,copy])=><section key={heading}><h2>{heading}</h2><p>{copy}</p></section>)}</div><p className="ee-journal-footnote">Fragrance performance is personal. Skin, clothing, weather, storage and application all influence how a profile develops and how long it remains noticeable.</p></article></main>;
}
